# Generated by Django 3.2.4 on 2021-06-23 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0004_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='nophoto.jpg', upload_to='products'),
        ),
    ]
